apiVersion: v2
name: sd-archive-services
description: "BIAN Service Domain: Archive Services (Maintain pattern, Business Support)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - maintain
annotations:
  bian/business-area: "Business Support"
  bian/business-domain: "Corporate Services"
  bian/asset-type: "Archive Item"
  bian/control-record: "Archive Item Maintenance Agreement"
